import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@workspace/ui/components/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@workspace/ui/components/table";
import { formatDistanceToNow } from "date-fns";
import { Trash2, Eye, Loader2, BookOpen } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { ConfirmDialog } from "@/components/confirm-dialog";
import { ContentLayout } from "@/components/layout/content-layout";
import { orpc } from "@/lib/orpc";

import { WikiPageDrawer } from "./wiki-page-drawer";

export function AdminWiki() {
  const queryClient = useQueryClient();
  const [viewingPageId, setViewingPageId] = useState<string | null>(null);
  const [deletingPageId, setDeletingPageId] = useState<string | null>(null);

  const { data, isPending } = useQuery({
    ...orpc.wikiPage.list.queryOptions({ input: { limit: 100, page: 1 } }),
  });

  const deleteMutation = useMutation(
    orpc.wikiPage.delete.mutationOptions({
      onError: (err) => {
        toast.error(`Failed to delete: ${err.message}`);
        setDeletingPageId(null);
      },
      onSuccess: () => {
        toast.success("WikiPage deleted");
        queryClient.invalidateQueries(
          orpc.wikiPage.list.queryOptions({ input: { limit: 100, page: 1 } })
        );
        setDeletingPageId(null);
      },
    })
  );

  const items = data?.items ?? [];

  return (
    <ContentLayout>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
            Wiki Pages
          </h1>
          <p className="text-muted-foreground text-sm mt-1">
            Wiki articles generated by the ingestion pipeline from uploaded
            documents.
          </p>
        </div>
      </div>

      <div className="mt-6">
        {isPending ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="animate-spin text-muted-foreground" size={24} />
          </div>
        ) : // oxlint-disable-next-line unicorn(no-nested-ternary)
        items.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <BookOpen size={40} className="text-muted-foreground mb-3" />
            <p className="font-medium">No wiki pages yet</p>
            <p className="text-sm text-muted-foreground mt-1">
              Wiki pages are automatically generated when documents are
              processed by the ingestion pipeline. Configure System AI settings
              to enable the pipeline.
            </p>
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Title</TableHead>
                <TableHead className="w-32 text-center">Sources</TableHead>
                <TableHead className="w-40">Updated</TableHead>
                <TableHead className="w-20" />
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((page) => (
                <TableRow key={page.id}>
                  <TableCell>
                    <button
                      className="font-medium hover:underline text-left"
                      onClick={() => setViewingPageId(page.id)}
                    >
                      {page.title}
                    </button>
                    <div className="text-xs text-muted-foreground mt-0.5">
                      /{page.slug}
                    </div>
                  </TableCell>
                  <TableCell className="text-center text-sm text-muted-foreground">
                    {page.sourceCount} doc{page.sourceCount !== 1 ? "s" : ""}
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {formatDistanceToNow(new Date(page.updatedAt), {
                      addSuffix: true,
                    })}
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1 justify-end">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() => setViewingPageId(page.id)}
                      >
                        <Eye size={14} />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-destructive hover:text-destructive"
                        onClick={() => setDeletingPageId(page.id)}
                      >
                        <Trash2 size={14} />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </div>

      {viewingPageId && (
        <WikiPageDrawer
          pageId={viewingPageId}
          onClose={() => setViewingPageId(null)}
        />
      )}

      <ConfirmDialog
        open={!!deletingPageId}
        onOpenChange={(open) => {
          if (!open) {
            setDeletingPageId(null);
          }
        }}
        title="Delete WikiPage"
        desc="This will permanently delete the wiki page and all its chunks and embeddings. This cannot be undone."
        handleConfirm={() => {
          if (deletingPageId) {
            deleteMutation.mutate({ id: deletingPageId });
          }
        }}
        isLoading={deleteMutation.isPending}
      />
    </ContentLayout>
  );
}
